"""
Spontaneous CP violation in the ECCG flavon sector:
can Delta_CP = 3 delta_2 - 2 delta_3 be PREDICTED instead of assumed?

Setup
-----
CP is imposed as an exact symmetry of the Lagrangian: ALL couplings real.
The harmonic couplings kappa_2, kappa_3 (phases delta_2 = arg kappa_2,
delta_3 = arg kappa_3, invariant Delta_CP = 3 delta_2 - 2 delta_3, cf.
FIRST_PRINCIPLES_DERIVATION.md Sec. 5) are generated by the VEV of a complex
flavon S = v e^{i theta}:

    kappa_2 = c_2 (S/M_f)^{n_2},   kappa_3 = c_3 (S/M_f)^{n_3},   c_i real,

so  delta_2 = n_2 theta (+0/pi),  delta_3 = n_3 theta (+0/pi), and

    Delta_CP = (3 n_2 - 2 n_3) theta  ==  m * theta   (mod pi from sign of c_i,
                                                       which drops mod 2pi
                                                       since m is even, see below).

theta is fixed by minimizing a CP-conserving (real-coefficient) potential.

Structural no-go theorems (verified in section 1 of __main__):
 (N1) If the flavon phase is aligned with the U(1)_Q rephasing (single flavon
      restoring U(1)_Q: n_2 q_S = -2 q_P, n_3 q_S = -3 q_P => n_2/n_3 = 2/3),
      then m = 3 n_2 - 2 n_3 = 0 identically: Delta_CP = 0, and theta is the
      Goldstone of the restored U(1)_Q. A single U(1)_Q-charged flavon CANNOT
      generate Delta_CP.
 (N2) A single Z_N-invariant harmonic V = b v^4 cos(N theta) has vacua at
      theta = pi j / N ("geometric" phases). Consistency of the Z_N in the P
      sector requires m = 3 n_2 - 2 n_3 = 0 mod N, so Delta_CP = m theta =
      pi j (m/N) in {0, pi} mod 2pi -- CP-CONSERVING. (Delta_CP = pi is the
      point where J_CP = Im(kappa_2^3 kappa_3*^2) = 0 and the psi-wall bias
      vanishes: asymmetry averages to zero over unbiased psi domains.)

Minimal working model (Z_2 flavor symmetry, renormalizable, section 2):
    V(S) = -m^2 |S|^2 + lam |S|^4
           + [ (mp2/2) S^2 + (lamp/4) S^4 + (lampp/2)|S|^2 S^2 + h.c. ],
    all coefficients REAL (CP), Z_2: S -> -S (so odd powers absent).
With S = v e^{i theta}, x = cos 2theta:
    V = -mu2(x) v^2 + Lam(x) v^4,
    mu2 = m^2 - mp2 x,   Lam = lam + lamp (2x^2 - 1)/2 + lampp x,
    V_min(theta) = -mu2^2 / (4 Lam)   at   v^2 = mu2/(2 Lam).
Phase-only limit (v frozen): V_theta = a cos 2theta + b cos 4theta with
a = mp2 v^2 + lampp v^4, b = lamp v^4 / 2; frustrated minimum
cos 2theta* = -a/(4b) exists iff b > 0 and |a| < 4b  =>  sin 2theta* != 0:
SPONTANEOUS CPV with a calculable phase. At the symmetric point a = 0:
theta* = pi/4 exactly => Delta_CP = pi/2 for the minimal embedding m = 2.

Embeddings (Z_2 consistency: (-1)^{n_2} eta^2 = 1, (-1)^{n_3} eta^3 = 1 with
P -> eta P, eta = +-1  =>  n_2 even; m = 3 n_2 - 2 n_3 is then always even):
    (n_2, n_3) = (2, 2):  m = 2   [minimal; headline]
    (n_2, n_3) = (2, 1):  m = 4
    (n_2, n_3) = (2, 3):  m = 0   [U(1)_Q-commensurate, no-go N1]

Section 3 scans the real coefficients and reports the distribution of
|Delta_CP| and sin(|Delta_CP|/2). Section 4 does the domain-wall checks
(flavon CP walls + Delta_CP-dependence of the existing psi-wall bias).
Section 5 does the strong-CP / Nelson-Barr estimates.

Run:  <repo>/.venv/bin/python spontaneous_cp.py
Outputs: spontaneous_cp_scan.csv, spontaneous_cp_summary.csv,
         delta_cp_distribution.png, walls_and_etaB.png
"""
from __future__ import annotations

import math
from pathlib import Path

import numpy as np
import pandas as pd

HERE = Path(__file__).resolve().parent
RNG = np.random.default_rng(20260712)

# ----------------------------------------------------------------------------
# Benchmark registry (values traced to development/dark_completion and
# development/parameter_reduction; see report for provenance).
# ----------------------------------------------------------------------------
MPL_GEV = 1.2209e19          # non-reduced Planck mass
MPL_RED = 2.435e18           # reduced Planck mass
Tn = 3.172132e12             # nucleation temperature (GeV)
gstar = 106.75
f_psi = 1.0217e13            # phase decay constant ~ condensate scale (GeV)
kappa2_bench = 1.4330760601e-4
c3_bench = 4.06477183236e-39  # kappa_3 / M^2 (GeV^-2)
A_WALL = 0.8                 # scaling-area parameter (as in domain_wall_history)
M_CUT = 4.0e17               # S_3 completion cutoff (COLLECTIVE_BREAKING Sec. 3)
M_MESS = 1.98e16             # messenger mass (S3_HARDENING working point)
YBYD = 2.55e-3               # bridge coupling ceiling y_b*y_d (channel D)
THETA_QCD_BOUND = 1.0e-10    # nEDM bound on theta_bar
ETA_OBS = 6.10e-10
ETA3_BENCH = 0.357           # fitted eta_3 (predict_eta_B.py benchmark)


def H_of_T(T):
    return 1.66 * math.sqrt(gstar) * T * T / MPL_GEV


def T_of_H(H):
    return math.sqrt(H * MPL_GEV / (1.66 * math.sqrt(gstar)))


def rho_rad(T):
    return math.pi ** 2 / 30.0 * gstar * T ** 4


def eta_B_of_sCP(sCP, eta3=1.0):
    """Calibrated forward model of predict_eta_B.py: eta_B ∝ eta_3 * sCP."""
    return ETA_OBS * (eta3 / ETA3_BENCH) * sCP


# ----------------------------------------------------------------------------
# The flavon potential (Z_2 model), reduced to x = cos(2 theta).
# Units: m^2 = 1 (all dimensionful quantities in units of m).
# ----------------------------------------------------------------------------
def V_min_of_x(x, mp2, lamp, lampp, lam=1.0, m2=1.0):
    """Depth of the potential at phase x = cos(2 theta), radial minimized.

    mu2 = m2 - mp2*x ; Lam = lam + lamp*(2x^2-1)/2 + lampp*x
    V_min = -mu2^2/(4 Lam) for mu2 > 0 (else v = 0, V = 0).
    Returns +inf where Lam <= 0 (unbounded direction -- draw rejected upstream).
    """
    mu2 = m2 - mp2 * x
    Lam = lam + lamp * (2.0 * x * x - 1.0) / 2.0 + lampp * x
    mu2 = np.maximum(mu2, 0.0)
    with np.errstate(divide="ignore", invalid="ignore"):
        V = -(mu2 * mu2) / (4.0 * Lam)
    return np.where(Lam > 0.0, V, np.inf)


def bounded(mp2, lamp, lampp, lam=1.0):
    """Quartic form positive for all theta: lam + lamp(2x^2-1)/2 + lampp x > 0."""
    x = np.linspace(-1.0, 1.0, 201)
    Lam = lam + lamp * (2.0 * x * x - 1.0) / 2.0 + lampp * x
    return Lam.min(axis=-1) > 1e-9


def minimize_flavon(mp2, lamp, lampp, lam=1.0, ngrid=4001):
    """Vectorized global minimization over x in [-1, 1] (grid + parabolic refine).

    Accepts scalar or 1-d arrays of coefficients. Returns (x*, theta*, v*, Vmin).
    """
    mp2 = np.atleast_1d(np.asarray(mp2, float))
    lamp = np.atleast_1d(np.asarray(lamp, float))
    lampp = np.atleast_1d(np.asarray(lampp, float))
    x = np.linspace(-1.0, 1.0, ngrid)
    V = V_min_of_x(x[None, :], mp2[:, None], lamp[:, None], lampp[:, None],
                   lam=lam)
    i = np.argmin(V, axis=1)
    # parabolic refinement (interior points only)
    ii = np.clip(i, 1, ngrid - 2)
    y0, y1, y2 = (V[np.arange(len(i)), ii - 1], V[np.arange(len(i)), ii],
                  V[np.arange(len(i)), ii + 1])
    denom = (y0 - 2 * y1 + y2)
    shift = np.where(np.abs(denom) > 1e-300, 0.5 * (y0 - y2) / denom, 0.0)
    shift = np.clip(shift, -1.0, 1.0)
    dx = x[1] - x[0]
    xstar = np.clip(x[ii] + shift * dx, -1.0, 1.0)
    xstar = np.where(i == 0, -1.0, np.where(i == ngrid - 1, 1.0, xstar))
    mu2 = np.maximum(1.0 - mp2 * xstar, 0.0)
    Lam = 1.0 * lam + lamp * (2 * xstar ** 2 - 1) / 2.0 + lampp * xstar
    vstar = np.sqrt(mu2 / (2.0 * Lam))
    Vstar = -(mu2 ** 2) / (4.0 * Lam)
    theta = 0.5 * np.arccos(np.clip(xstar, -1, 1))
    return xstar, theta, vstar, Vstar


def fold_pi(delta):
    """Fold an angle to [0, pi] (|Delta_CP| mod 2pi, using the +-theta* pair)."""
    d = np.mod(delta, 2.0 * np.pi)
    return np.where(d > np.pi, 2.0 * np.pi - d, d)


# ----------------------------------------------------------------------------
# Section 4 helpers: domain walls.
# ----------------------------------------------------------------------------
def psi_wall_margin(delta_cp):
    """Collapse/domination margin of the psi (second-harmonic) walls vs Delta_CP.

    domain_wall_history.py used bias delta_V = 2 A_3 (implicitly |cos(dCP/2)|=1).
    With the two Z_2 minima psi = 0, pi (basis delta_2 = 0, delta_3 = -dCP/2):
        bias = |V(pi) - V(0)| = 2 A_3 |cos(Delta_CP/2)|.
    T_c ∝ sqrt(H_c) ∝ sqrt(bias)  =>  margin(dCP) = margin_0 sqrt(|cos(dCP/2)|).
    """
    rho = f_psi
    A2 = 0.5 * kappa2_bench * rho ** 4
    A3 = 0.25 * c3_bench * rho ** 6
    m2m = 2.0 * math.sqrt(A2) / f_psi
    sigma = 2.0 * m2m * f_psi ** 2
    cosfac = np.abs(np.cos(np.asarray(delta_cp) / 2.0))
    Hc = 2.0 * A3 * cosfac / sigma
    Tc = np.sqrt(Hc * MPL_GEV / (1.66 * math.sqrt(gstar)))
    Tdom2 = (A_WALL * sigma * 1.66 * math.sqrt(gstar) / MPL_GEV) / (
        math.pi ** 2 / 30.0 * gstar)
    Tdom = math.sqrt(Tdom2)
    return Tc / Tdom


def flavon_wall_tension_coeff(mp2, lamp, lampp, lam=1.0, npts=4000):
    """sigma_S = k * v_S^3 for the CP walls between theta* and its images.

    Canonical phase field chi = v theta at frozen v = v(theta*);
    sigma_hat = v^2 * int sqrt(2 (V(theta) - V_min)) dtheta along the lower of
    the two barrier paths (through theta = 0 or theta = pi/2).
    Returns k = sigma_hat / v_hat^3 (dimensionless; sigma_phys = k v_S^3).
    """
    xstar, tstar, vstar, Vstar = minimize_flavon(mp2, lamp, lampp, lam=lam)
    tstar, vstar, Vstar = float(tstar[0]), float(vstar[0]), float(Vstar[0])

    def Vth(th):
        x = np.cos(2 * th)
        mu2 = 1.0 - mp2 * x
        Lam = lam + lamp * (2 * x ** 2 - 1) / 2.0 + lampp * x
        return -mu2 * vstar ** 2 + Lam * vstar ** 4

    sig = []
    for a, b in [(-tstar, tstar), (tstar, np.pi - tstar)]:  # via 0, via pi/2
        th = np.linspace(a, b, npts)
        dV = np.maximum(Vth(th) - Vth(tstar), 0.0)
        sig.append(vstar * np.trapezoid(np.sqrt(2.0 * dV), th))
    return min(sig) / vstar ** 3, tstar, vstar


# ----------------------------------------------------------------------------
# __main__
# ----------------------------------------------------------------------------
def main():
    summary = {}
    print("=" * 72)
    print("SPONTANEOUS CP VIOLATION IN THE FLAVON SECTOR: predicting Delta_CP")
    print("=" * 72)

    # ---------------- Section 1: structural no-gos --------------------------
    print("\n--- (1) structural no-go checks ---")
    # N1: U(1)_Q-commensurate single flavon: n2/n3 = 2/3 => m = 0.
    for k in (1, 2, 3):
        n2, n3 = 2 * k, 3 * k
        m = 3 * n2 - 2 * n3
        assert m == 0
    print("  N1: single U(1)_Q-charged flavon (n2/n3 = 2/3): m = 3n2-2n3 = 0")
    print("      => Delta_CP = 0 IDENTICALLY (and theta = U(1)_Q Goldstone).")

    # N2: single Z_N harmonic => geometric vacua, Delta_CP in {0, pi}.
    print("  N2: single Z_N-invariant harmonic V = b v^4 cos(N theta):")
    rows_n2 = []
    for N, n2, n3 in [(2, 2, 3), (2, 4, 3), (4, 2, 1), (4, 2, 5), (3, 2, 3),
                      (6, 2, 3), (6, 4, 3)]:
        m = 3 * n2 - 2 * n3
        assert m % N == 0, "Z_N inconsistent embedding"
        for sb in (+1.0, -1.0):
            # vacua of sb*cos(N theta): N theta = pi (sb>0) or 0 (sb<0), + 2pi j
            th_min = (np.pi if sb > 0 else 0.0) / N
            vac = [th_min + 2 * np.pi * j / N for j in range(N)]
            dcp = sorted({round(float(fold_pi(m * t)), 10) for t in vac})
            rows_n2.append((N, n2, n3, m, sb, dcp))
            assert all(abs(d) < 1e-9 or abs(d - np.pi) < 1e-9 for d in dcp)
    for N, n2, n3, m, sb, dcp in rows_n2:
        print(f"      Z_{N}, (n2,n3)=({n2},{n3}), m={m:+d}, sign(b)={sb:+.0f}: "
              f"Delta_CP in {{{', '.join(f'{d:.4f}' for d in dcp)}}}")
    print("      => always CP-conserving ({0, pi}). FRUSTRATION IS REQUIRED.")
    summary["no_go_single_harmonic"] = "Delta_CP in {0,pi} (verified)"

    # ---------------- Section 2: minimal Z_2 frustrated model ---------------
    print("\n--- (2) minimal Z_2 flavon model (renormalizable, real couplings) ---")
    # symmetric point: a = 0 (mp2 = lampp = 0), lamp > 0
    x0, t0, v0, V0 = minimize_flavon(0.0, 0.5, 0.0)
    d0 = float(fold_pi(2 * t0[0]))
    print(f"  symmetric point (mp2=lampp=0, lamp=0.5):"
          f" theta* = {float(t0[0]):.6f} = pi/4? {abs(float(t0[0])-np.pi/4)<1e-6}")
    print(f"    => Delta_CP(m=2) = {d0:.6f} rad = pi/2 EXACTLY;"
          f" sin(dCP/2) = {math.sin(d0/2):.4f}")
    summary["dCP_symmetric_point_m2"] = d0

    # representative generic point
    bench = dict(mp2=0.30, lamp=0.50, lampp=-0.20)
    xb, tb, vb, Vb = minimize_flavon(**bench)
    xb, tb, vb = float(xb[0]), float(tb[0]), float(vb[0])
    # phase-only analytic cross-check at frozen v = v*:
    a = bench["mp2"] * vb ** 2 + bench["lampp"] * vb ** 4
    b = bench["lamp"] * vb ** 4 / 2.0
    x_analytic = -a / (4.0 * b)
    dcp2 = float(fold_pi(2 * tb))
    dcp4 = float(fold_pi(4 * tb))
    print(f"  benchmark point {bench}:")
    print(f"    v* = {vb:.6f} (units of m/sqrt(lam)), theta* = {tb:.6f} rad")
    print(f"    cos2theta*: exact = {xb:.6f}, phase-only analytic -a/4b = "
          f"{x_analytic:.6f}  (agree to {abs(xb-x_analytic):.1e})")
    print(f"    Delta_CP(m=2) = {dcp2:.4f} rad, sin(dCP/2) = {math.sin(dcp2/2):.4f}")
    print(f"    Delta_CP(m=4) = {dcp4:.4f} rad, sin(dCP/2) = {math.sin(dcp4/2):.4f}")
    summary.update(dCP_bench_m2=dcp2, sinhalf_bench_m2=math.sin(dcp2 / 2),
                   dCP_bench_m4=dcp4, x_check_residual=abs(xb - x_analytic))

    # ---------------- Section 3: coefficient scan ---------------------------
    print("\n--- (3) coefficient scan: distribution of Delta_CP ---")
    NDRAW = 40000
    draws = []
    while sum(len(d) for d in draws) < NDRAW:
        n = NDRAW
        mp2 = RNG.choice([-1, 1], n) * 10 ** RNG.uniform(-2, 0, n)
        lamp = RNG.choice([-1, 1], n) * 10 ** RNG.uniform(-2, 0, n)
        lampp = RNG.choice([-1, 1], n) * 10 ** RNG.uniform(-2, 0, n)
        ok = bounded(mp2[:, None], lamp[:, None], lampp[:, None])
        draws.append(np.column_stack([mp2[ok], lamp[ok], lampp[ok]]))
    arr = np.vstack(draws)[:NDRAW]
    frac_bounded = arr.shape[0] / sum(len(d) for d in draws) if draws else 1.0

    xs, ts, vs, Vs = [], [], [], []
    for lo in range(0, NDRAW, 4000):
        x_, t_, v_, V_ = minimize_flavon(arr[lo:lo + 4000, 0],
                                         arr[lo:lo + 4000, 1],
                                         arr[lo:lo + 4000, 2])
        xs.append(x_); ts.append(t_); vs.append(v_); Vs.append(V_)
    x = np.concatenate(xs); th = np.concatenate(ts)
    v = np.concatenate(vs); Vm = np.concatenate(Vs)

    cpv = np.abs(x) < 1.0 - 1e-4          # sin 2theta* != 0  <=> SCPV
    d2 = fold_pi(2 * th)                   # |Delta_CP|, embedding m = 2
    d4 = fold_pi(4 * th)                   # embedding m = 4
    s2 = np.sin(d2 / 2.0)
    s4 = np.sin(d4 / 2.0)

    fcpv = cpv.mean()
    lamp_pos = arr[:, 1] > 0
    print(f"  draws: {NDRAW} (couplings: random sign x log-uniform [1e-2,1];"
          f" bounded fraction of raw draws = {frac_bounded:.3f})")
    print(f"  SCPV fraction (sin 2theta* != 0): {fcpv:.3f}")
    print(f"    given lamp > 0 (frustrating sign): {cpv[lamp_pos].mean():.3f}")
    print(f"    given lamp < 0:                    {cpv[~lamp_pos].mean():.3f}")
    q = lambda z, p: float(np.percentile(z, p))
    for tag, dd, ss in [("m=2", d2, s2), ("m=4", d4, s4)]:
        dd_c, ss_c = dd[cpv], ss[cpv]
        print(f"  embedding {tag} (CPV draws only, N={cpv.sum()}):")
        print(f"    |Delta_CP|: median = {q(dd_c,50):.3f} rad,"
              f" 16-84% = [{q(dd_c,16):.3f}, {q(dd_c,84):.3f}],"
              f" 5-95% = [{q(dd_c,5):.3f}, {q(dd_c,95):.3f}]")
        print(f"    sin(|dCP|/2): median = {q(ss_c,50):.3f},"
              f" 16-84% = [{q(ss_c,16):.3f}, {q(ss_c,84):.3f}]")
        print(f"    P(sin(|dCP|/2) > 0.3) = {(ss_c>0.3).mean():.3f};"
              f" P(within 0.2 rad of 0 or pi) = "
              f"{((dd_c<0.2)|(dd_c>np.pi-0.2)).mean():.3f}")
    summary.update(
        scpv_fraction=fcpv, scpv_fraction_lamp_pos=float(cpv[lamp_pos].mean()),
        dCP_m2_median=q(d2[cpv], 50), dCP_m2_p16=q(d2[cpv], 16),
        dCP_m2_p84=q(d2[cpv], 84), dCP_m2_p05=q(d2[cpv], 5),
        dCP_m2_p95=q(d2[cpv], 95),
        sinhalf_m2_median=q(s2[cpv], 50), sinhalf_m2_p16=q(s2[cpv], 16),
        sinhalf_m2_p84=q(s2[cpv], 84),
        dCP_m4_median=q(d4[cpv], 50),
        sinhalf_m4_median=q(s4[cpv], 50),
        frac_near_cp_conserving_m2=float(((d2[cpv] < 0.2) |
                                          (d2[cpv] > np.pi - 0.2)).mean()),
    )

    # eta_B with the predicted phase (eta_3 = 1, calibrated forward model)
    eta_med = eta_B_of_sCP(q(s2[cpv], 50))
    eta_lo = eta_B_of_sCP(q(s2[cpv], 16))
    eta_hi = eta_B_of_sCP(q(s2[cpv], 84))
    print(f"  eta_B (eta_3 = 1, m=2 spontaneous phase): median = {eta_med:.2e},"
          f" 16-84% = [{eta_lo:.2e}, {eta_hi:.2e}]  (observed {ETA_OBS:.2e})")
    summary.update(eta_B_median=eta_med, eta_B_p16=eta_lo, eta_B_p84=eta_hi)

    df = pd.DataFrame(dict(mp2=arr[:, 0], lamp=arr[:, 1], lampp=arr[:, 2],
                           x_star=x, theta_star=th, v_star=v, V_min=Vm,
                           cpv=cpv, dCP_m2=d2, sin_half_m2=s2,
                           dCP_m4=d4, sin_half_m4=s4))
    df.to_csv(HERE / "spontaneous_cp_scan.csv", index=False)

    # ---------------- Section 4: domain walls -------------------------------
    print("\n--- (4) domain walls ---")
    # 4a: psi-walls -- Delta_CP-dependence of the existing bias.
    margin0 = float(psi_wall_margin(0.0))
    cos_min = (1.0 / margin0) ** 2
    dcp_max = 2.0 * math.acos(cos_min)
    print(f"  (4a) psi-walls: bias = 2 A_3 |cos(dCP/2)|; margin(dCP) = "
          f"{margin0:.2f} sqrt(|cos(dCP/2)|)")
    print(f"       margin < 1 (UNSAFE) iff |Delta_CP| > {dcp_max:.4f} rad "
          f"(within {np.pi-dcp_max:.4f} of pi)")
    m_med = float(psi_wall_margin(q(d2[cpv], 50)))
    frac_unsafe = float((d2[cpv] > dcp_max).mean())
    print(f"       at the median predicted dCP = {q(d2[cpv],50):.3f}: margin = "
          f"{m_med:.2f}x; fraction of CPV draws unsafe = {frac_unsafe:.4f}")
    print("       NOTE: Delta_CP = pi is doubly dead: J_CP = 0 AND bias = 0"
          " (stable psi walls, asymmetry averages to 0 over domains).")
    summary.update(psi_margin_dCP0=margin0, psi_dCP_unsafe_above=dcp_max,
                   psi_margin_at_median=m_med, psi_frac_unsafe=frac_unsafe)

    # 4b: flavon CP walls -- exactly degenerate (CP exact), must be inflated away.
    k_sig, tb2, vb2 = flavon_wall_tension_coeff(**bench)
    # flavon scale, two branches (see report):
    vS_A = M_CUT * math.sqrt(kappa2_bench)           # c_2 = 1, M_f = M_cut
    vS_B = MPL_RED * math.sqrt(THETA_QCD_BOUND)      # theta_bar-safe ceiling
    Mf_B = vS_B / math.sqrt(kappa2_bench)            # mediator scale for kappa_2
    print(f"  (4b) flavon CP walls (theta* <-> pi - theta*): tension "
          f"sigma_S = {k_sig:.3f} v_S^3 (benchmark point)")
    for tag, vS in [("A (c2=1, M_f=M_cut)", vS_A), ("B (theta_bar-safe)", vS_B)]:
        sig = k_sig * vS ** 3
        Tdom = math.sqrt((A_WALL * sig * 1.66 * math.sqrt(gstar) / MPL_GEV)
                         / (math.pi ** 2 / 30.0 * gstar))
        print(f"       branch {tag}: v_S = {vS:.2e} GeV, sigma_S = {sig:.2e} "
              f"GeV^3;")
        print(f"         if Kibble-formed: would dominate at T = {Tdom:.2e} GeV "
              f"with NO bias possible (CP exact, all real ops are even in "
              f"theta) -> MUST be inflated away;")
        print(f"         requirement T_RH < T_S ~ v_S: window T_RH in "
              f"[{Tn:.2e}, {vS:.2e}] GeV, factor {vS/Tn:.1f}")
    summary.update(flavon_wall_k=k_sig, vS_branch_A=vS_A, vS_branch_B=vS_B,
                   Mf_branch_B=Mf_B, TRH_window_A=vS_A / Tn,
                   TRH_window_B=vS_B / Tn)

    # ---------------- Section 5: strong CP ----------------------------------
    print("\n--- (5) strong CP / Nelson-Barr ---")
    print("  theta_bar(tree) = 0 EXACTLY: CP exact => theta_QCD = 0 and quark")
    print("  Yukawas real; the flavon has no tree coupling to colored fields.")
    sin_dcp = 1.0  # worst case
    th_grav_A = (vS_A / MPL_RED) ** 2 * sin_dcp
    th_grav_B = (vS_B / MPL_RED) ** 2 * sin_dcp
    th_rad = (YBYD / (16 * math.pi ** 2)) ** 2 * (f_psi / M_MESS) ** 2 * sin_dcp
    print(f"  gravity-induced dim-6  (S^2/M_Pl^2) q_bar H q  (if not forbidden):")
    print(f"    branch A (v_S = {vS_A:.2e}): theta_bar ~ {th_grav_A:.2e}  "
          f"{'FAILS' if th_grav_A > THETA_QCD_BOUND else 'OK'} vs 1e-10"
          f" -> needs gauged Z_N (N >= 4) forbidding S^n q_bar H q, n < 4")
    n_needed = math.ceil(math.log(THETA_QCD_BOUND) / math.log(vS_A / MPL_RED))
    print(f"      (smallest safe power: (v_S/M_Pl)^n < 1e-10 needs n >= "
          f"{n_needed})")
    print(f"    branch B (v_S = {vS_B:.2e} = sqrt(1e-10) M_Pl): theta_bar ~ "
          f"{th_grav_B:.2e}  == bound (marginal by construction);"
          f" kappa_2 then needs flavon mediator M_f = {Mf_B:.2e} GeV < M_cut OK")
    print(f"  radiative feed-through via the messenger bridge "
          f"(y_b y_d = {YBYD}, m_mess = {M_MESS:.2e}):")
    print(f"    theta_bar ~ (y_b y_d/16pi^2)^2 (rho/m_mess)^2 sin(dCP) ~ "
          f"{th_rad:.2e}  << 1e-10  SAFE")
    print("  => Nelson-Barr-like: CP broken only in the sequestered flavon/dark")
    print("     sector; the SAME messenger sequestering already required for")
    print("     thermal survival (channel D ceiling) protects theta_bar.")
    summary.update(theta_bar_tree=0.0, theta_bar_grav_A=th_grav_A,
                   theta_bar_grav_B=th_grav_B, theta_bar_radiative=th_rad,
                   grav_power_needed_A=n_needed)

    # ---------------- plots --------------------------------------------------
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    fig, ax = plt.subplots(1, 2, figsize=(11, 4.2))
    bins = np.linspace(0, np.pi, 80)
    ax[0].hist(d2[cpv], bins=bins, density=True, alpha=0.65,
               label=r"$m=2$ (minimal)", color="C0")
    ax[0].hist(d4[cpv], bins=bins, density=True, alpha=0.45,
               label=r"$m=4$", color="C1")
    ax[0].axvline(np.pi / 2, ls="--", c="k", lw=1,
                  label=r"symmetric point $\pi/2$")
    ax[0].axvspan(dcp_max, np.pi, color="r", alpha=0.15,
                  label=r"$\psi$-walls unsafe")
    ax[0].set_xlabel(r"$|\Delta_{\rm CP}|$ [rad]")
    ax[0].set_ylabel("density (SCPV draws)")
    ax[0].set_title(r"Spontaneous $\Delta_{\rm CP}$ over real coefficients")
    ax[0].legend(fontsize=8)

    dgrid = np.linspace(1e-3, np.pi - 1e-3, 400)
    ax[1].plot(dgrid, np.sin(dgrid / 2), label=r"$\eta_B \propto \sin(\Delta/2)$")
    ax[1].plot(dgrid, psi_wall_margin(dgrid) / margin0,
               label=r"wall margin / margin$_0$ $= \sqrt{|\cos(\Delta/2)|}$")
    ax[1].axvspan(dcp_max, np.pi, color="r", alpha=0.15)
    ax[1].axvline(q(d2[cpv], 50), ls=":", c="C0",
                  label=f"median prediction {q(d2[cpv],50):.2f}")
    ax[1].set_xlabel(r"$|\Delta_{\rm CP}|$ [rad]")
    ax[1].set_title(r"Baryogenesis vs $\psi$-wall bias: complementarity")
    ax[1].legend(fontsize=8)
    fig.tight_layout()
    fig.savefig(HERE / "delta_cp_distribution.png", dpi=150)

    fig2, ax2 = plt.subplots(1, 2, figsize=(11, 4.2))
    thg = np.linspace(0, np.pi, 600)
    for lab, p in [("symmetric (a=0)", dict(mp2=0.0, lamp=0.5, lampp=0.0)),
                   ("benchmark", bench),
                   ("CP-conserving (lamp<0)",
                    dict(mp2=0.3, lamp=-0.5, lampp=-0.2))]:
        xg = np.cos(2 * thg)
        Vg = V_min_of_x(xg, p["mp2"], p["lamp"], p["lampp"])
        ax2[0].plot(thg, Vg - Vg.min(), label=lab)
    ax2[0].set_xlabel(r"$\theta_S$"); ax2[0].set_ylabel(r"$V(\theta_S)-V_{min}$")
    ax2[0].set_title("Flavon phase potential (radially minimized)")
    ax2[0].legend(fontsize=8)
    sc = ax2[1].scatter(arr[cpv, 1], (arr[cpv, 0] + arr[cpv, 2] * v[cpv] ** 2),
                        c=d2[cpv], s=2, cmap="twilight", vmin=0, vmax=np.pi)
    ax2[1].set_xscale("log")
    ax2[1].set_xlabel(r"$\lambda'$ (frustrating quartic)")
    ax2[1].set_ylabel(r"$a/v^2 = m'^2 + \lambda'' v^2$ (aligning term)")
    ax2[1].set_title(r"$|\Delta_{\rm CP}|$ ($m=2$) over the SCPV region")
    plt.colorbar(sc, ax=ax2[1], label=r"$|\Delta_{\rm CP}|$")
    fig2.tight_layout()
    fig2.savefig(HERE / "walls_and_etaB.png", dpi=150)

    pd.DataFrame([summary]).T.rename(columns={0: "value"}).to_csv(
        HERE / "spontaneous_cp_summary.csv")
    print("\nWrote spontaneous_cp_scan.csv, spontaneous_cp_summary.csv,")
    print("      delta_cp_distribution.png, walls_and_etaB.png")

    # ---------------- bottom line -------------------------------------------
    print("\n--- BOTTOM LINE ---")
    print(f"  Spontaneous CP gives a CALCULABLE Delta_CP = m theta_S (m even).")
    print(f"  Frustrated minimum needed (single harmonic => 0 or pi, no-go).")
    print(f"  Minimal Z_2 model, m=2: symmetric point predicts dCP = pi/2;")
    print(f"  over coefficients: median {q(d2[cpv],50):.2f} rad, generic O(1),")
    print(f"  sin(dCP/2) median {q(s2[cpv],50):.2f}; SCPV in {fcpv*100:.0f}% of")
    print(f"  coefficient space (the rest is CP-conserving: sign-dependent).")


if __name__ == "__main__":
    main()
